installed_mcps:
  notion:
    type: "local"
    source: "npx -y @notionhq/notion-mcp-server"
    description: "Official Notion MCP Server"
    env_vars:
      NOTION_API_TOKEN: "${NOTION_API_TOKEN}"
      NOTION_API_KEY: "${NOTION_API_KEY}"
    enabled: true

  # Additional examples
  # github:
  #   type: "docker"
  #   source: "ghcr.io/github/github-mcp-server"
  #   description: "GitHub's official MCP server"
  #   env_vars:
  #     GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_TOKEN}"
  #   enabled: false