installed_mcps:
  # Keep only MCPs you actively use. Examples below are commented out.
  # Enable by setting `enabled: true` and providing required env vars.
  #
  # github:
  #   type: "docker"
  #   source: "ghcr.io/github/github-mcp-server"
  #   description: "GitHub's official MCP server"
  #   env_vars:
  #     GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_TOKEN}"
  #   enabled: false