installed_mcps:
  notion:
    type: "local"
    source: "npx -y @notionhq/notion-mcp-server"
    description: "Official Notion MCP Server"
    env_vars:
      NOTION_API_TOKEN: "${NOTION_API_TOKEN}"
      NOTION_API_KEY: "${NOTION_API_KEY}"
    enabled: true